doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Post:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Post/Entity'
                prefix: 'Stessaluna\Domain\Post\Entity'
                alias: Post
            TextPost:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Post/Text/Entity'
                prefix: 'Stessaluna\Domain\Post\Text\Entity'
                alias: TextPost
            ExercisePost:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Post/Exercise/Entity'
                prefix: 'Stessaluna\Domain\Post\Exercise\Entity'
                alias: ExercisePost
            Exercise:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Exercise/Entity'
                prefix: 'Stessaluna\Domain\Exercise\Entity'
                alias: Exercise
            AorbExercise:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Exercise/Aorb/Entity'
                prefix: 'Stessaluna\Domain\Exercise\Aorb\Entity'
                alias: AorbExercise
            Answer:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Exercise/Answer/Entity'
                prefix: 'Stessaluna\Domain\Exercise\Answer\Entity'
                alias: Answer
            AorbAnswer:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Exercise/Answer/Aorb/Entity'
                prefix: 'Stessaluna\Domain\Exercise\Answer\Aorb\Entity'
                alias: AorbAnswer
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/User/Entity'
                prefix: 'Stessaluna\Domain\User\Entity'
                alias: User
            Comment:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Post/Comment/Entity'
                prefix: 'Stessaluna\Domain\Post\Comment\Entity'
                alias: Comment
