doctrine:
  dbal:
    url: "%env(resolve:DATABASE_URL)%"
    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '5.7'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      Post:
        is_bundle: false
        type: annotation
        dir: "%kernel.project_dir%/src/Post/Entity"
        prefix: 'Stessaluna\Post\Entity'
        alias: Post
      Exercise:
        is_bundle: false
        type: annotation
        dir: "%kernel.project_dir%/src/Exercise/Entity"
        prefix: 'Stessaluna\Exercise\Entity'
        alias: Exercise
      AorbExercise:
        is_bundle: false
        type: annotation
        dir: "%kernel.project_dir%/src/Exercise/Aorb/Entity"
        prefix: 'Stessaluna\Exercise\Aorb\Entity'
        alias: AorbExercise
      WhatdoyouseeExercise:
        is_bundle: false
        type: annotation
        dir: "%kernel.project_dir%/src/Exercise/Whatdoyousee/Entity"
        prefix: 'Stessaluna\Exercise\Whatdoyousee\Entity'
        alias: WhatdoyouseeExercise
      Answer:
        is_bundle: false
        type: annotation
        dir: "%kernel.project_dir%/src/Exercise/Answer/Entity"
        prefix: 'Stessaluna\Exercise\Answer\Entity'
        alias: Answer
      User:
        is_bundle: false
        type: annotation
        dir: "%kernel.project_dir%/src/User/Entity"
        prefix: 'Stessaluna\User\Entity'
        alias: User
      Comment:
        is_bundle: false
        type: annotation
        dir: "%kernel.project_dir%/src/Post/Comment/Entity"
        prefix: 'Stessaluna\Post\Comment\Entity'
        alias: Comment
