lexik_jwt_authentication:
  secret_key: "%env(resolve:JWT_SECRET_KEY)%"
  public_key: "%env(resolve:JWT_PUBLIC_KEY)%"
  pass_phrase: "%env(JWT_PASSPHRASE)%"

  token_ttl: 28800 # 8 hours

  token_extractors:
    # look for a token in the Authorization Header
    authorization_header:
      enabled: true
      prefix: Bearer
      name: Authorization

    # look for a token in a cookie
    cookie:
      enabled: true
      name: access_token
