env:
  # jest: true
  browser: true
  es6: true
extends: "plugin:react/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - unused-imports
rules:
  {
    "no-unused-vars": "off",
    "no-undef": 2,
    "unused-imports/no-unused-imports": 2,
    "unused-imports/no-unused-vars": 1,
    "semi": [2, "always"],
  }
