default_controller:
  resource: ../../src/DefaultController.php
  type: annotation

auth_controller:
  resource: ../../src/Auth/Controller/
  type: annotation

user_controller:
  resource: ../../src/User/Controller/
  type: annotation

post_controller:
  resource: ../../src/Post/Controller/
  type: annotation

comment_controller:
  resource: ../../src/Post/Comment/Controller/
  type: annotation

exercise_controller:
  resource: ../../src/Exercise/Controller/
  type: annotation
