default_controller:
    resource: ../../src/Api/Controller/
    type: annotation

security_controller:
    resource: ../../src/Api/Security/Controller/
    type: annotation

user_controller:
    resource: ../../src/Api/User/Controller/
    type: annotation

post_controller:
    resource: ../../src/Api/Post/Controller/
    type: annotation

comment_controller:
    resource: ../../src/Api/Post/Comment/Controller/
    type: annotation

exercise_controller:
    resource: ../../src/Api/Exercise/Controller/
    type: annotation